server:
  port: 9191
  
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: http://localhost:2000
          predicates:
            - Path=/api/products/**
        - id: INVENTORY-SERVICE
          uri: http://localhost:3000
          predicates:
            - Path=/api/inventorys/**
        - id: CUSTOMER-SERVICE
          uri: http://localhost:1342
          predicates:
            - Path=/api/customers/**
        - id: ORDER-SERVICE
          uri: http://localhost:4848
          predicates:
            - Path=/api/orders/**
        - id: CART-SERVICE
          uri: http://localhost:5000
          predicates:
            - Path=/api/carts/**